/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { MockERC20Token } from "./MockERC20Token";
export type { ProjectSubmission } from "./ProjectSubmission";
export type { Staking } from "./Staking";
